<a href="https://colab.research.google.com/github/trottiemcqueen/Angular-E-Commerce-Store/blob/main/003_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Manipulating tensors (basic operations)

***Basic Operations***

+, -, *, /

In [ ]:
import tensorflow as tf
import numpy as np

# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor = tensor - 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

# When using *, and / there is no need to create a variable to apply basic operation

In [ ]:
# We can use tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Matrix multiplication with tensors part 1

## In machine learning, matrix multiplication is one of the most common tensor operations.

## There are two rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them:

  1. The inner dimensions must match
  2. The resulting matrix has the shape of the inner dimensions.

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor) # matrix multiplication

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Create a (3, 2) tensor
x = tf.constant([[3, 4],
                 [8, 9],
                 [5, 6]])
# Create another (3, 2) tensor
y = tf.constant([[3, 4],
                 [5, 6],
                 [7, 8]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [8, 9],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape


***Resource*** : Info and example of matrix multiplication: https://www.mathsisfun.com/algrbra/matrix-multiplying.html

In [ ]:
# Create a (3, 2) tensor
x = tf.constant([[3, 4],
                 [8, 9],
                 [5, 6]])
# Create another (3, 2) tensor
y = tf.constant([[3, 4],
                 [5, 6],
                 [7, 8]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [8, 9],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape, '@' and 'matmul' will not work
# Lets change the shape of Y
tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
x.shape, tf.reshape(y, shape=(2, 3)).shape # Helps me understand big picture

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Lets try to matrix multiply x by reshaped y
x @ tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 33,  40,  47],
       [ 78,  95, 112],
       [ 51,  62,  73]], dtype=int32)>

In [ ]:
# Tried to change the shape of x instead of y
tf.matmul(tf.reshape(x, shape=(2, 3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 85, 100],
       [ 94, 114]], dtype=int32)>

In [ ]:
tf.reshape(x, shape=(2, 3)).shape, tf.reshape(y, shape=(2, 3)).shape

(TensorShape([2, 3]), TensorShape([2, 3]))

In [ ]:
# What about with transpose
x, tf.transpose(x), tf.reshape(x, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [8, 9],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 8, 5],
        [4, 9, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 4, 8],
        [9, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(x), y) # transpose flips the axis rather than shuffling

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 84, 100],
       [ 99, 118]], dtype=int32)>

***The dot product***
### Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tesnordot()`

In [ ]:
# Perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 84, 100],
       [ 99, 118]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between x and y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 25,  39,  53],
       [ 60,  94, 128],
       [ 39,  61,  83]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between x and y (reshaped)
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 33,  40,  47],
       [ 78,  95, 112],
       [ 51,  62,  73]], dtype=int32)>

### I have get used to reshaping a lot, from my understanding it will become a neccassary requirement

***NOTE*** : One of the most common errors you're going to get in writing neural network code are misshaped tensors and even more just as common, but deceivingly a deceiving error.

That is when your tensors line up with shape but the outputs that you're getting. So you get no error message, it just works.

So it's important then to be able to investigate what's going on and figure out what's called a silent error, is that when your code works like no error, it's outputted from the code itself. But the results just clearly aren't correct.

So this is the sort of thing that I will do to investigate those silent errors, to transpose 'why' that's what we want to do.

In [ ]:
# Check the values of y, reshape y and transposed y
print("Normal y:")
print(y, "\n") # "\n" is for newLine

print("y reshaped to (2, 3):")
print(tf.reshape(y, (2, 3)), "\n")

print("y transposed:")
print(tf.transpose(y))

Normal y:
tf.Tensor(
[[3 4]
 [5 6]
 [7 8]], shape=(3, 2), dtype=int32) 

y reshaped to (2, 3):
tf.Tensor(
[[3 4 5]
 [6 7 8]], shape=(2, 3), dtype=int32) 

y transposed:
tf.Tensor(
[[3 5 7]
 [4 6 8]], shape=(2, 3), dtype=int32)


## Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

### Next is Changing the datatype of a tensor

In [ ]:
import tensorflow as tf
import numpy as np

# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([5, 11])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 5., 11.], dtype=float32)>

### Aggregating tensors

Aggregating tensors: break down from multi values to smaller values

In [ ]:
import tensorflow as tf
import numpy as np

Zz = tf.constant([-9, -10])
Zz


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -9, -10], dtype=int32)>

In [ ]:
tf.abs(Zz)# abs stands for absolute value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 10], dtype=int32)>

The following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 - 100 of sizze 50
Pp = tf.constant(np.random.randint(0, 100, size=50))
Pp

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([22, 12, 35, 31, 32, 36, 41, 43, 37, 69, 37, 93, 50, 72, 16, 98, 75,
       48, 99, 59, 89, 62, 31,  9, 41,  2, 12,  9, 89,  9, 16, 38,  4, 23,
       35, 91, 87, 93, 36, 37, 90, 10, 53, 34, 42,  6, 63, 70, 17, 40])>

In [ ]:
tf.size(Pp), Pp.shape, Pp.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(Pp)


<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
np.min(Pp)

2

In [ ]:
# The Variance and standard deviation of Pp using TensorFlow methods.

import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(Pp)

<tf.Tensor: shape=(), dtype=int64, numpy=821>

In [2]:
# To find the variance of our tensor, we need access to tensorflow_probability
import tensorflow_probability as tfp


import numpy as np
import tensorflow as tf



In [4]:
# Find the standard deviation and float32 is usually the standard type
tf.math.reduce_std(tf.cast(Pp, dtype=tf.float32))

# Now going to find the positional maximum and minimum